# Generated by Django 2.2.18 on 2021-03-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210326_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_title',
            field=models.CharField(max_length=20),
        ),
    ]
