# Generated by Django 2.2.18 on 2021-07-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210622_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_title', models.CharField(max_length=100)),
            ],
        ),
    ]
