# Generated by Django 2.2.18 on 2021-07-17 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_test_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_data',
        ),
    ]
