# Generated by Django 2.2.18 on 2021-03-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='Категория отсутствует', on_delete=True, to='blog.Category'),
        ),
    ]
