# Generated by Django 2.2.18 on 2021-04-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210414_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.ManyToManyField(to='blog.Comment'),
        ),
    ]
