# Generated by Django 2.2.18 on 2021-04-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_title',
            new_name='comment_text',
        ),
    ]
