# Generated by Django 2.2.18 on 2021-11-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211114_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
