# Generated by Django 2.2.18 on 2021-03-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210304_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='blog.Category', verbose_name='Category'),
        ),
    ]
