# Generated by Django 2.2.18 on 2021-12-04 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211204_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='rating',
            order_with_respect_to='post',
        ),
    ]
