# Generated by Django 2.2.18 on 2021-12-04 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20211204_0213'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='rating',
            order_with_respect_to='post_id',
        ),
    ]
