# Generated by Django 2.2.18 on 2021-12-04 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20211204_0214'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='rating',
            order_with_respect_to='post',
        ),
    ]
