# Generated by Django 2.2.18 on 2021-12-04 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20211204_0217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['post_id']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='rating',
            order_with_respect_to=None,
        ),
    ]
