# Generated by Django 2.2.18 on 2021-03-13 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210310_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='category_title',
        ),
    ]
