# Generated by Django 2.2.18 on 2021-12-04 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20211204_0219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('post',)},
        ),
    ]
