# Generated by Django 2.2.18 on 2021-12-10 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20211204_0223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
    ]
