# Generated by Django 2.2.18 on 2021-03-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
